version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user123"
      POSTGRES_PASSWORD: "pass123"
    ports:
      - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
  cart-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "cart-api"
    restart: always
    volumes:
      - "./config/config.yml:/build/config.yml"
    ports:
      - "8080:8080"
volumes:
  data: